title: Megha Mehta
description: Fashion & Lifestyle
authorName: Megha Mehta
authorImage: /img/uploads/megz.png
items:
  - icon: ion-logo-facebook
    link: 'https://www.facebook.com/mehta.megz'
    name: Facebook
  - icon: ion-logo-instagram
    link: 'https://www.instagram.com/megz_mehta/'
    name: Instagram
  - icon: ion-ios-mail
    link: 'mailto:mehta.megz@gmail.com'
    name: Email
instagramProfileUrl: 'https://www.instagram.com/megz_mehta/'
instagramUserId: '1614935030'
instagramAccessToken: 1614935030.1677ed0.388bd15127d2432cbed3d77641048e09
googleAnalyticsId: '12'
